name: chromm_bayes_opt
channels:
  - conda-forge
dependencies:
  - python==3.9
  - addict==2.3
  - bayesian-optimization
  - h5py
  - joblib
  - matplotlib
  - numpy
  - pandas
  - pip
  - SALib
  - scipy
  - scikit-learn
  - smt
  - statsmodels
